---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: yolo-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: activity
  template: 
    metadata: 
      labels: 
        app: activity
    spec: 
      containers: 
        - 
          image: activity-detection/cv:latest
          imagePullPolicy: Never
          name: activity
          volumeMounts:
            -   
              mountPath: /root/data/
              name: yolo-data-volume
            - 
              mountPath: /root/workspace/cv/
              name: yolo-code-volume
          # command: ["/bin/sh"]
          # args: ["-c", "python3 /root/workspace/cv/yolo.py"]
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          ports:
            - 
              containerPort: 3306     
        - 
          image: activity-detection/shadow:latest
          imagePullPolicy: Never
          name: rpi-shadow
          volumeMounts:
            - 
              mountPath: /root/data/
              name: yolo-data-volume
            - 
              mountPath: /root/workspace/shadow/
              name: shadow-code-volume
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          ports:
            - 
              containerPort: 3307
      volumes:
        - 
          name: yolo-data-volume
          hostPath:
            path: /Users/dakanwang/workspace/on_premise/
            type: Directory
        - 
          name: shadow-code-volume
          hostPath:
            path: /Users/dakanwang/workspace/ActivityDetection/
            type: Directory    
        - 
          name: yolo-code-volume
          hostPath:
            path: /Users/dakanwang/workspace/ActivityDetection/
            type: Directory
        


---
kind: Service
apiVersion: v1
metadata:
  name: activity-service
spec:
  selector:
    app: activity
  ports:
    - 
      protocol: TCP
      type: ClusterIP
      port: 3306